version: 2.1

orbs:
  python: cjw296/python-ci@2.1

jobs:
  coverage:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - attach_workspace:
          at: coverage_output
      - run:
          name: "Check coverage"
          command: |
            sudo pip install coverage
            coverage combine coverage_output/
            bash <(curl -s https://codecov.io/bash)

common: &common
  jobs:

    - python/pip-run-tests:
        matrix:
          parameters:
            image:
              - circleci/python:2.7
              - circleci/python:3.6
              - circleci/python:3.9

    - coverage:
        name: coverage
        requires:
          - python/pip-run-tests
workflows:
  push:
    <<: *common
  periodic:
    <<: *common
    triggers:
      - schedule:
          cron: "0 0 11 * *"
          filters:
            branches:
              only: master
